### ISSUE TITLE
Add context to panic message in Must

### ISSUE THREAD

**Issue by CorentinClabaut** [samber/lo#139]
It would be great to be able to add context to the panic message in `Must`.
That would be especially useful in the case where `Must` validates a boolean as at the moment it panics with the message "not ok".

I was thinking we could add the parameter `msgAndArgs ...interface{}` at the end of each `Must` function like it is done in the assert functions of the `testify` package.

 We could then call it like that for example:
```go
lo.Must0(strings.Contains(myString, requiredSubString)), "'%s' must always contain '%s'", myString, requiredSubString)
```

Note:
One issue with the solution described above is that the compiler will not detect when the number of values returned by the function used in `Must` doesn't match the expected number of parameters of `Must`. 

One solution for that could be to create new function like `MustF` & `MustFX` which take a string instead of `msgAndArgs ...interface{}`

For the same example we would then have:
```go
lo.MustF0(strings.Contains(myString, requiredSubString)), fmt.Sprintf("'%s' must always contain '%s'", myString, requiredSubString))
```

**Comment by samber** [comment]
Hi @CorentinClabaut and thanks for this contribution.

I really like the idea of the custom panic message.

Your note is relevant. I think we can improve the documentation to make it clear to developers. Also, your panic message is nice to describe this case `"must: invalid err type 'xxxx', should either be a bool or an error"`.
