### ISSUE TITLE
Add Take()

### ISSUE THREAD

**Issue by hut8** [samber/lo#162]
`Take` would be great for `lo`, because it's somewhat hard in Go using the built-in slice syntax:

https://lodash.com/docs/#take

``` js
_.take([1, 2, 3]);
// => [1]
 
_.take([1, 2, 3], 2);
// => [1, 2]
 
_.take([1, 2, 3], 5);
// => [1, 2, 3]
 
_.take([1, 2, 3], 0);
// => []
```

In Go, it's tempting to do this to get the first (up to) 5 elements in a slice:

```go
s := []int{1,2,3}
s[:5]
// panic
```

So `lo` could do this better:

```go
s := []int{1,2,3}
lo.Take(s, 2)
// => []int{1,2}
lo.Take(s, 5)
// => []int{1,2,3}
// and not panic 😊
```

I will open a PR.

**Comment by samber** [comment]
Hi @hut8 

In that case, you can use `Slice([]int{1,2,3}, 0, 2)` or `Subset([]int{1,2,3}, 0, 2)`.

I consider we don't need yet another helper here.
