### ISSUE TITLE
Add Slice()

### ISSUE THREAD

**Issue by Nonua** [samber/lo#168]
Hi

Currently `slice[start:end]` makes the code crash when out of range, JavaScript/[lodash slice function](https://lodash.com/docs/4.17.15#slice) takes care to not panic if out of range.

Potential usage:
```
i := []int{1,2,3,4,5}
sliced := lo.Slice(i, 1, 10)
// sliced = []int{2,3,4,5}
```

The function I am using: (which checks out of range only for `end`)
```
func Slice[T any](t []T, start int, end int) []T {
	length := len(t)
	if end > length {
		end = length
	}
	return t[start:end]
}
```

**Comment by samber** [comment]
Thanks @Nonua for this first contribution ;)

**Comment by Nonua** [comment]
Thank you @samber, I am having a blast learning Go and lo has been a great leap forward to do so
