### ISSUE TITLE
Filtering a slice by a value or a list of values

### ISSUE THREAD

**Issue by renom** [samber/lo#170]
For example:
`lo.FilterValue[int]([]int{0, 0, 1, 2, 3, 3, 4}, 3) // returns []int{0, 0, 1, 2, 4}`
`lo.FilterValues[int]([]int{0, 0, 1, 2, 3, 3, 4}, []int{1, 3, 4}) // returns []int{0, 0, 2}`
`lo.FilterEmptyValues[int]([]int{0, 0, 1, 2, 3, 3, 4}) // returns []int{1, 2, 3, 3, 4}`
I mean, I know there is `lo.Difference`, but it returns two values.

**Comment by DillonStreator** [comment]
Seems unnecessary IMO. Do you find [`lo.Filter`](https://github.com/samber/lo/blob/master/slice.go#L7-L18) to be too verbose?

```go
lo.Filter([]int{0,0,1,2,3,3,4}, func(num int) {
  return num != 3
})
```

```go
numsToRemove := map[int]struct{}{
  1: struct{},
  3: struct{},
  4: struct{},
}

lo.Filter([]int{0,0,1,2,3,3,4}, func(num int) {
  _, ok := numsToRemove[num]
  return !ok
})
```

etc...

**Comment by samber** [comment]
You can use `lo.Without` and `lo.WithoutEmpty` 👇

```go
lo.Without[int]([]int{0, 0, 1, 2, 3, 3, 4}, 3)
lo.Without[int]([]int{0, 0, 1, 2, 3, 3, 4}, 1, 3, 4)
lo.WithoutEmpty[int]([]int{0, 0, 1, 2, 3, 3, 4})
```
