### ISSUE TITLE
lo.Else() Should not be Triggered If lo.If() is True

### ISSUE THREAD

**Issue by KiddoV** [samber/lo#174]
I have an If-Else to check if the length of the slice is <= 0. If it is true then return ``10``, but I expected the ``lo.Else()`` function will NOT trigger because the ``lo.If()`` is already true and return.
In normal If-Else statement, it won't execute the ``Else`` in this case.
```go
package main

import (
	"fmt"

	"github.com/samber/lo"
)

func main() {
	testArr := []int{}
	result := lo.If(len(testArr) <= 0, 10).Else(testArr[0]) //This will be panic: index out of range!!!
	fmt.Println(result)
}
```
How do I fix this?

**Comment by samber** [comment]
You can fix this with a lazy execution:

```go
result := lo.If(len(testArr) <= 0, 10).ElseF(func () int {
    return testArr[0]
})
```

**Comment by KiddoV** [comment]
@samber I was hoping to have ``1 liner If-Else statement``. How do I make it 1 liner?

**Comment by samber** [comment]
`result := lo.If(len(testArr) <= 0, 10).ElseF(func () int { return testArr[0] })` ? 😆 

Sorry, there is no better way to write it... :-(

**Comment by KiddoV** [comment]
My IDE (VS Code) would break the line in haft anyway. 😢
But If-Else statement should behaves like the original right? Is it hard to fix the logic behind ``lo.If-Else``? I'm new to ``golang``, sorry I couldn't make any PR.

**Comment by samber** [comment]
In JS, ternary are evaluated lazily. But calling `Else(testArr[0])` will send put the `testArr[0]` value into the `Else` argument, then `Else` is executed.

This is equivalent to:

```go
arg := testArr[0]
result := lo.If(len(testArr) <= 0, 10).Else(arg)
```
