### ISSUE TITLE
Error is Associate documentation? Should Associate have an alias SliceToMap?

### ISSUE THREAD

**Issue by CorentinClabaut** [samber/lo#191]
It feels like SliceToMap is more explanatory of what the function does and more consistent with the naming of the function `lo.MapToSlice`.

Another issue with Associate is that the documentation says:
`The returned map preserves the entry iteration order of the original array.` 
But that shouldn't be the case as in golang the map is implemented as a hash table.

**Comment by samber** [comment]
I agree. I made a change: a4816ee5ff61752d99b0cd601ccfcb06458125c9
