### ISSUE TITLE
Tuple Item Getter support?

### ISSUE THREAD

**Issue by wrouesnel** [samber/lo#198]
Suppose I have a list of tuples:

```go
conversionResult := []lo.Tuple[string,bool]{ T2("x",true), T2("x",false), T2("x",false), T2("x",true)  }
```
This is the sort of list you get from doing a Map of type-assertions and need to catch errors.

I now want to convert this ergonomically into just the list of one element or another. I could do this with another map, like:

```go
// Flatten the valid list out to []string
s := lo.Map(conversionResult, func(t lo.Tuple2[string, bool], _ int) string {
  value, _ := lo.Unpack2(t)
  return value
})
```

Which is a bit of a nothing function to repeat. What I'd like to do instead is something like:

```go
s:= lo.Map(conversionResult, lo.Get(0))
```

and have that yank every 0th element out of the tuples.

The python equivalent operation (which is very convenient) would be:

```python
import operator

conversion_result = [ ("x",True),("x",False),("x",False),("x",True) ]
s = list(map(operator.itemgetter(0), conversion_result))
```

Obviously the limitations of Go make making it totally concise perhaps not possible, but a matched set of operator functions for the T2->9 tuple types feels like it would be in-scope for the library and lead to cleaner code. Something like:

or even just a set of direct extractors:
```go
s := lo.Map(conversionResult, lo.Get2A)
s := lo.Map(conversionResult, lo.Get2B)
```

**Comment by VipinRaiP** [comment]
Shall i take up this issue? @samber

**Comment by samber** [comment]
Hi there

Nice to see you here @wrouesnel . I really like your work on postgres_exporter project ;)

Why don't you use Unzip2 instead?

```go
tuple := []lo.Tuple[string,bool]{ T2("x",true), T2("x",false), T2("x",false), T2("x",true)  }
strings, bools := lo.Unzip2(tuple)
```

The `operator.itemgetter(0)`/`lo.Get(0)` helper is not typesafe. I would rather not add such functions. `lo.Get2A` could be an option, but I add complexity for little gains.

`s := lo.Map(conversionResult, lo.Get2B)` can we replaced by `_, s := lo.Unzip2(conversionResult)`

**Comment by wrouesnel** [comment]
Huh, that does look like a complete solution to the problem. Thanks!
