### ISSUE TITLE
Must: Multiple values in single value context 

### ISSUE THREAD

**Issue by adrianplavka** [samber/lo#227]
Using `Must` function in Go 1.19, as described in the examples:

```go
val := lo.Must(lo.Find(myString, func(i string) bool {
    return i == requiredChar
}), "'%s' must always contain '%s'", myString, requiredChar)
``` 

will produce an error:

`multiple-value lo.Find(myString, func(i string) bool {…}) (value of type (string, bool)) in single-value context`

**Comment by samber** [comment]
Hi @adrianplavka 

Thanks for the report. I made a fix 👌

**Comment by Ifaliuk** [comment]
Hi. It still doesn't work. when can you fix it?

**Comment by samber** [comment]
I just fixed the doc actually.

Go does not allow to inject multiple arguments into the middle of argument list.

you have to do that:

```go
blabla, ok := lo.Find(myString, func(i string) bool {
    return i == requiredChar
})
val := lo.Must(blabla, ok, "'%s' must always contain '%s'", myString, requiredChar)
```

**Comment by Ifaliuk** [comment]
thanks
