### ISSUE TITLE
How to use the `lo` more easily

### ISSUE THREAD

**Issue by SimFG** [samber/lo#254]
For example, if I want to iterate over the `names` collection, I will type `lo.ForEach(names, func...)`.
I need to complete the generics type and look that the function need to fill those params in the `GoLand`.

I will spend more time filling relevant content than using a for statement. I don't know if there is a suitable plugin here to solve this problem.

**Comment by samber** [comment]
I'm not sure to understand your issue.

If a "for" loop looks better, why not using it?

2 cases not supported by "for" loop:

- passing a callback, such as lo.ForEach(items, myCallback)
- "copy" problem: in a "for" loop, next value has the same memory address, so you cannot use it as a pointer. ForEach solves that issue.

**Comment by SimFG** [comment]
When I use some `lo` method, I don't know how many parameters this function takes and what are the parameter types. If I don't look at the source implementation of this function, I will not be able to use this function. But if the parameter of a function is a function type, I only need to enter `func`, goland will give a prompt, and then press Enter, I can complete the structure of the function, including which parameters are required, what types of parameters, and return results.
![20221024-214115](https://user-images.githubusercontent.com/21985684/197539889-98b72a79-4e52-4713-900d-7cce5db7d5d8.gif)

**Comment by SimFG** [comment]
About the second case, 
"copy" problem: in a "for" loop, next value has the same memory address, so you cannot use it as a pointer. ForEach solves that issue.

I can't understand it.  Can you can write an example to explain it. Thank you.

**Comment by samber** [comment]
About autocompletion in your code editor:

- You should not have to tell Goland that `[T]` is of type `string`, since it should be inferred from the `names` variable.
- I suppose your code editor does not have proper autocompletion settings. I work well in my VSCode setup.

**Comment by samber** [comment]
I use the following extension: https://marketplace.visualstudio.com/items?itemName=golang.Go

**Comment by SimFG** [comment]
Thanks for your detailed answers.
