### ISSUE TITLE
Add IsSome function

### ISSUE THREAD

**Issue by CorentinClabaut** [samber/lo#281]
One pattern I often see in my code is something like this:
```go
if var == "x" || var == "y" {
  ...
}
```

It feels like in this situation, it would be useful to have a function like this:
`func IsSome[T comparable](value T, possibilities []T) bool`
or even something like:
`func IsSome[T comparable](value T, possibility1 T, possibility2 T, otherPossibilities T...) bool`

Then we could write:
`if lo.IsSome(var, []string{"x", "y") {`
or:
`if lo.IsSome(var, "x", "y") {` (Which is more concise but maybe more confusing?)

Using a function like `IsSome` has the following advantages over writing multiple comparison:
  - No duplication of the variable name
  - More concise
  - Reads better

It could be worth having the opposite function `IsNone` as well, even though it's just the same as having `!IsSome`.

Admittedly we could just use the function `lo.Contains` but using this function in this case looks a bit confusing to me.
`if lo.Contains([]string{"x", "y"}, var) {`

@samber If that's an addition you could be interested in I'm happy to create a PR for it.
Also I thought of the name `IsSome` to be consistent with the existing `Some` and `SomeBy` functions but there might be better names for it like maybe `IsAny`?

**Comment by samber** [comment]
Hi @CorentinClabaut and thanks for this new suggestion.

I'm not sure to understand what is the value of IsSome, compared to Contains. 🤔

BTW, the va-arg variant looks confusing to me. Somebody reading a code for the first time won't be able to understand what we are comparing.

**Comment by CorentinClabaut** [comment]
That might be overkill.
I'll close the issue.
