### ISSUE TITLE
`Substring` can't handle utf8 characters

### ISSUE THREAD

**Issue by trim21** [samber/lo#286]
```golang
package main

import (
	"fmt"

	"github.com/samber/lo"
)

func main() {
	result1 := lo.Substring("你好，世界", 0, 2)

	fmt.Printf("%s\n", result1)
}
```

https://go.dev/play/p/hvwkx8BQxPN

when processing string, it's expected to do something like this: `string(lo.Subset([]rune(s), start, end))`

**Comment by trim21** [comment]
@samber new release please?

**Comment by samber** [comment]
The v1.38.0 release failed. I just made a new version: v1.38.1.
