### ISSUE TITLE
Merge 2 Slices Into a Map

### ISSUE THREAD

**Issue by KiddoV** [samber/lo#291]
Is there a function to merge 2 slices into a map like this?
```go
keys := []string{"key1", "key2", "key3", "key4"}
data := []int{1, 2, 3, 4}

resultMap := lo.MergeSlices(keys, data)
//Required same length for 2 slices...
//Expecting result: map[string]int{"key1": 1, "key2": 2, "key3": 3, "key4": 4}
```
Thanks!

**Comment by mprimeaux** [comment]
I believe you're looking for [SliceToMap](https://github.com/samber/lo#associate-alias-slicetomap).

**Comment by Musab-Nazir** [comment]
I could be wrong in my current understanding but doesn't `Associate` take only one slice as input? So to create a map from 2 slices using Associate, you would need to first interleave the two slices and then partition by two or something so you have key value pairs that your transform func returns.

That seems like a lot more work then just running a simple for loop to create the map. So I do think there is value to having a function like OP describes

**Comment by samber** [comment]
I would compose `lo.Zip2` and `lo.Associate` together.

**Comment by KiddoV** [comment]
@samber  Can you give some sample code? Thanks!

**Comment by samber** [comment]
https://go.dev/play/p/P4kFDI9_yXI

**Comment by KiddoV** [comment]
Thanks, close this issue now!
