### ISSUE TITLE
The random string function always return the same value

### ISSUE THREAD

**Issue by nam-truong-le** [samber/lo#293]
The function returns different values in sequential calls but the initial value is always the same:

```go
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"

	"github.com/samber/lo"
)

func main() {
	result1 := lo.RandomString(5, lo.LettersCharset)
	result2 := lo.RandomString(5, lo.LettersCharset)

	fmt.Printf("%v %v", result1, result2)
}
```

Do I need to provide any seed value?

**Comment by mprimeaux** [comment]
Based on [this reference](https://github.com/samber/lo/blob/17e921399f52c2a0f805307ad3245295c2a168d5/string.go#L19) to [this playground](https://go.dev/play/p/rRseOQVVum4), it doesn't seem so.

The first run generated `pubyc` and the second run generated `CIhQr`.

**Comment by samber** [comment]
Since go 1.20, `rand.Seed(...)` is executed automatically at program startup.

https://pkg.go.dev/math/rand#Seed
