### ISSUE TITLE
eager evaluate for the else case : lo.Ternary

### ISSUE THREAD

**Issue by kcmvp** [samber/lo#294]
please see the reproduce code, it's supposed to return 0, but it runs into out of range exception

https://go.dev/play/p/0TtjJzKoWVp

**Comment by TWRaven** [comment]
The condition is still lazily evaluated, but the last parameter is `arr[0]`. This will already create an exception before `lo.Ternary` will run.

Use `lo.TernaryF` instead:
```go
var arr []int
result := lo.TernaryF(len(arr) == 0 || arr[0] < 0, func() int { return 0 }, func() int { return arr[0] })

fmt.Printf("%v", result)
```
https://go.dev/play/p/_wz2IM94fOb

**Comment by kcmvp** [comment]
Thank you! I will have a try!
