### ISSUE TITLE
Intersect function returns an unexpected result

### ISSUE THREAD

**Issue by Elephmoon** [samber/lo#303]
In case when you have two collections 
- first with one element
- second with many similar elements to the first
Intersect will return repeated len(secondCollection) times firstCollection element.
In my head Intersect should return firstCollection once in this case.
<img width="953" alt="image" src="https://user-images.githubusercontent.com/16652418/215861864-e8684d39-dda3-4f69-a0ea-8434ff39097f.png">

**Comment by ghostsquad** [comment]
agreed, this PR was made to address this very problem: #47

**Comment by Elephmoon** [comment]
Thanks. I believe I can close this issue, because problem will be solved when https://github.com/samber/lo/pull/47 will be merged.

**Comment by wmcnamee-coreweave** [comment]
#47 has not be merged, this issue should be re-opened to indicate that this problem still exists.

**Comment by ghostsquad** [comment]
It looks like intersect _was_ updated, sometime between when I created my PR, and now, so this issue can probably be closed.
