### ISSUE TITLE
For value range query copy slice and map problem

### ISSUE THREAD

**Issue by mhmtszr** [samber/lo#343]
When I review the implementations
```go
func Map[T any, R any](collection []T, iteratee func(item T, index int) R) []R {
	result := make([]R, len(collection))

	for i, item := range collection {
		result[i] = iteratee(item, i)
	}

	return result
}
```
Instead of for queries like these we can use
```go
func Map[T any, R any](collection []T, iteratee func(item T, index int) R) []R {
	result := make([]R, len(collection))

	for i := range collection {
		result[i] = iteratee(collection[i], i)
	}

	return result
}
```

This will prevent copying the slice and map. What do you think?

**Comment by RaddadZ** [comment]
according to benchmark tests in this answer: [performance of for range in go](https://stackoverflow.com/a/75857056/4779929), the difference between copying and using index isn't that much. 
Using the index to reach the value would make it changeable, thus the original collection will be changed after producing a new collection as a result of this map function.

**Comment by mhmtszr** [comment]
I didn't do any benchmarks for them interesting discussion thanks @RaddadZ.
