### ISSUE TITLE
Reduce lines of code

### ISSUE THREAD

**Issue by wuye251** [samber/lo#378]
When I reading the source code, found that can reduce the number of lines [like this](https://github.com/samber/lo/blob/2a744340d5ae20d374a2a3b774b1df965b4b0e12/slice.go#L139C1-L144). But I'm not sure it's the right thing to do, because it makes the code less readable. If it's right I would be happy to claim and optimize it.
```go
if _, ok := seen[key]; !ok {
    seen[key] = struct{}{}
    result = append(result, item)
}
```

**Comment by betoop** [comment]
The code was written in that way because [guard clauses ](https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html) are preferable for code readability.
