### ISSUE TITLE
The `lo.If'result` executed when `lo.If'condition` is false.

### ISSUE THREAD

**Issue by hwx98** [samber/lo#403]
```
type Person struct {
	Name string
	Age  int
}

type Person2 struct {
	*Person
}

var p2 *Person2
nn := lo.If(false, p2.Name).Else("no name")
fmt.Println(nn)
```
response:
exit status 2](panic: runtime error: invalid memory address or nil pointer dereference)

**Comment by lennon-guan** [comment]
You can use lo.IfF instead of lo.If

`
lo.IfF(false, func() string { return p2.Name }).Else(" no name")
`

**Comment by MorningBells** [comment]
why lo.If get "invalid memory address or nil pointer dereference"

**Comment by MorningBells** [comment]
thanks
