### ISSUE TITLE
propose: Add First() on slice, empty to return nil

### ISSUE THREAD

**Issue by kangarooxin** [samber/lo#437]

**Comment by freeeverett** [comment]
When the null value is not nil, I think the function cannot be implemented. Is there any way to implement the function?

**Comment by Alireza-Kiani** [comment]
Hey there, just created a pull request similar to what you need https://github.com/samber/lo/pull/451.
Returning zero value instead of `nil` is just more compatible with the conventions

**Comment by shivamrazorpay** [comment]
this is fixed.

**Comment by shivamrazorpay** [comment]
Issued fixed in : https://github.com/samber/lo/pull/451

**Comment by shivamrazorpay** [comment]
@kangarooxin as the issue is fixed, i think you can close it.
