### ISSUE TITLE
TYPO: Maybe a typo in Readme.md

### ISSUE THREAD

**Issue by ppzz** [samber/lo#463]
line 1564 in README file, `ch`  maybe a typo I think 

```
        items, length, _, ok := lo.BufferWithTimeout(ch, 1000, 1*time.Second)
        
        // should be
         items, length, _, ok := lo.BufferWithTimeout(c, 1000, 1*time.Second)
```

Is that so?

**Comment by ivila** [comment]
![image](https://github.com/samber/lo/assets/11420684/e3461de4-f1d6-4f6f-a1f4-d2bfd0147e26)
apparently not a typo, it should be **ch** as the variable is **ch** but not **c**

**Comment by samber** [comment]
closing, as there is no typo

**Comment by ppzz** [comment]
It seems I have misunderstood something. apologize.

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
oh okay
