### ISSUE TITLE
breaking changes to Last() in 1.42.0

### ISSUE THREAD

**Issue by nicwaller** [samber/lo#493]
I noticed that version [`v1.42.0`](https://github.com/samber/lo/releases/tag/v1.42.0) has some breaking changes that are not mentioned in the release notes. Specifically, #474 (5aa64ef28065731ccf3472b016d3079d5ee341b3) changes the return type of `Last()`:

- before `(T, error)`
- after `(T, bool)`

This is a breaking change that requires downstream consumers of `samber/lo` to make changes. As you're probably aware, [backward-compatibility is highly valued in Go modules](https://go.dev/blog/module-compatibility).

Please consider updating the release notes for `v1.42.0` to mention this breaking change. 🙏

**Comment by samber** [comment]
You're right. I made a change.
