### ISSUE TITLE
Proposal: TryOr7

### ISSUE THREAD

**Issue by Isteb4k** [samber/lo#532]
Think about this scenario

// TryOr7 has the same behavior as Must, but returns a default value in case of error.
// Play: https://go.dev/play/p/B4F7Wg2Zh9X
func TryOr7[A, B, C, D, E, F, G any](callback func() (A, B, C, D, E, F, G error), fallbackA A, fallbackB B, fallbackC C, fallbackD D, fallbackE E, fallbackF F, fallback G) (A, B, C, D, E, F, G bool) {
	ok := false

	Try0(func() {
		a, b, c, d, e, f, g, err := callback()
		if err == nil {
			fallbackA = a
			fallbackB = b
			fallbackC = c
			fallbackD = d
			fallbackE = e
			fallbackF = f
			fallbackG = g
			ok = true
		}
	})

	return fallbackA, fallbackB, fallbackC, fallbackD, fallbackE, fallbackF, fallbackG, ok
}

**Comment by universal-itengineer** [comment]
Hopefully we'll get that feature soon.
