### ISSUE TITLE
Add `All`, `Any` for reducing to `bool`

### ISSUE THREAD

**Issue by elliot-midnight** [samber/lo#54]
`All[T any](collection []T, predicate func (T) bool) bool` would return `true` if all the elements pass the predicate and short-circuit to `false` otherwise.

`Any[T any](collection []T, predicate func (T) bool) bool` would return `false` if none the elements pass the predicate and short-circuit to `true` otherwise.

These are common functions in Rust, Haskell, many other languages.

**Comment by samber** [comment]
Thanks for your contributions @muety and @CorentinClabaut .

We already have 2 similar functions: `Every` and `Some`. With following prototypes:

```go
func Every[T comparable](collection []T, subset []T) bool

func Some[T comparable](collection []T, subset []T) bool
```

In this package, a lot of functions are getting a `....By()` declination.

For a better developer XP, I wonder if we should bring closer your functions such as:

```go
func Every[T comparable](collection []T, subset []T) bool
func EveryBy[T comparable](collection []T, predicate func(V) bool) bool

func Some[T comparable](collection []T, subset []T) bool
func SomeBy[T comparable](collection []T, predicate func(V) bool) bool

func None[T comparable](collection []T, subset []T) bool
func NoneBy[T comparable](collection []T, predicate func(V) bool) bool
```

WDYT?

**Comment by CorentinClabaut** [comment]
Good point.
I have update my PR to implement these functions. #67
