### ISSUE TITLE
Add function for maps to receive slice of values filtered by given keys

### ISSUE THREAD

**Issue by metalrex100** [samber/lo#56]
Such function could be named like `ValuesF` which means `Values Filtered` or may be you suggest another naming.

The implementation is just an extension of the std lib `slices.Values` function:

```
ValuesF[K comparable, V any](m ~map[K]V, keys []K) []V {
	r := make([]V, 0, len(m))
	for k, v := range m {
		if slices.Contains(keys, k) {
			r = append(r, v)
		}
	}
	return r
}
```

**Comment by metalrex100** [comment]
I may suggest PR if needed.

**Comment by samber** [comment]
Hi @metalrex100 and thanks for the contribution.

I would rather choose `ValuesFilter` for a more explicit naming

But I think this helper does too many things.

Why not implementing:
- OmitByKeys(map, keysToRemove)
- OmitByValues(map, valuesToRemove)
- OmitBy(map, predicate)
- PickByKeys(map, keysToKeep)
- PickByValues(map, valuesToKeep)
- PickBy(map, predicate)

Your `ValuesF` function could be replaced by:

```go
subset := lo.PickByKeys(map[string]int{"foo": 1, "bar": 2, "baz": 3}, []string{"foo", "baz"})
values := lo.Values(subset)
```

WDYT ?

**Comment by metalrex100** [comment]
@samber I thing that `PickByKeys` is a more clear naming for such functionality, indeed. Will change it.

**Comment by samber** [comment]
I justed added:

- OmitByKeys(map, keysToRemove)
- OmitByValues(map, valuesToRemove)
- OmitBy(map, predicate)
- PickByValues(map, valuesToKeep)
- PickBy(map, predicate)
