### ISSUE TITLE
[BUG] `AttemptWhileWithDelay` (and presumably the other `Attempt...`s) does not behave a described (and expected).

### ISSUE THREAD

**Issue by milkpirate** [samber/lo#562]
I have the following set up:

```golang
_, _, err := lo.AttemptWhileWithDelay(0, time.Second, func(_ int, _ time.Duration) (error, bool) {
  return nil, true
})
```
From the description
> Invokes a function N times until it returns valid output, with a pause between each call. Returns either the caught error or nil, along with a bool value to determine whether the function should be invoked again. It will terminate the invoke immediately if the second return value is false.
>
> When the first argument is less than 1, the function runs until a successful response is returned.

I would expect the above to be equivalent to
```golang
for {}
```
But terminates after the first try. This is since the `err == nil` and https://github.com/samber/lo/blob/master/retry.go#L225. From the description, and from a usage point of view, I would expect that the retry flag takes precedence over the `err` value which it doesnt.

Is that by design? Would you please clarify in the documentation if so and if not fix the source.

**Comment by nekomeowww** [comment]
It works as intended.

Because the error returned is nil. And as `until it returns valid output` has described, `nil` for `error` is considered valid, if you wish to achieve `for {}`, you can return `errors.New("continue")`, or perhaps, define:

```go
var Continue = errors.New("continue")

func main() {
  _, _, err := lo.AttemptWhileWithDelay(0, time.Second, func(_ int, _ time.Duration) (error, bool) {
    return Continue, true
  })
}
```

**Comment by milkpirate** [comment]
Ok, to me it sounded like I control the "valid output condition" via the boolean return. Ok, will close this issue, but maybe you still want to consider reworking the documentation.
