### ISSUE TITLE
Typo in doc

### ISSUE THREAD

**Issue by metalrex100** [samber/lo#59]
`ContainsBy` example has `Contains` title.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/22449118/159310151-6dc0431b-b8b3-4855-9807-84e6b271b4c5.png">

**Comment by yangchnet** [comment]
Also, I find `UniqBy` has `Uniq` title.
![image](https://user-images.githubusercontent.com/30308940/159658486-f219b72f-8767-4b1f-8071-862ef565065a.png)
