### ISSUE TITLE
Suggestion: FindIndex function

### ISSUE THREAD

**Issue by jalavosus** [samber/lo#61]
The `Find` function exists. The `IndexOf` function exists. What would be super helpful is a `FindIndex` function; similar in mechanics to `Find`, except it returns the slice index of the first slice member which satisfies the `Find` function (or -1 if none are found). 

Awesome project, by the way!

**Comment by metalrex100** [comment]
@jalavosus I think the implementation may be done like this:
```
func FindIndex[T any](collection []T, predicate func(T) bool) (int, bool) {
	for index, item := range collection {
		if predicate(item) {
			return index, true
		}
	}
	return 0, false
}```
