### ISSUE TITLE
Suggestion: Add Coalesce-like Function

### ISSUE THREAD

**Issue by DouglasMartins1999** [samber/lo#96]
I'm new to Go lang community, so this is most a discussion about if it'd be a good practice than a suggestion by itself. Coming from the Javascript world, it is common to see situations where this expression is used:

```javascript
function (arg1, arg2) {
    return arg1 ?? arg2 ?? "[default value]"
}
```

In SQL databases it is also common to find the Coalesce function that solves a similar problem:

```sql
SELECT COALESCE(column1, column2, '[default value]')
FROM xyz
```

But I didn't find in Go a simple way to handle nil values and use a default value instead, needing to use the `Ternary()` or `Find()` functions as a solution, but still they don't seem to be the most idiomatic way to solve the problem. Following examples above, it might be interesting to have functions like:

`Coalesce():` Returns the first non-nil argument passed to the function
`NullIf():` Returns nil if both arguments are equal, otherwise returns the first

**Comment by samber** [comment]
Good idea!

Feel free to propose an implementation.

Coalesce should accept a variadic argument.

**Comment by wirekang** [comment]
I think this issue should be closed.
